### ISSUE TITLE
Heep of errors

### ISSUE THREAD

**Issue by DuckersMcQuack** [fo76utils/ce2utils#2]
I've never done this before, so please point out what i might be missing. 

Followed every step of the tutorials, here, as well as here: https://modding.wiki/en/starfield/developers/tutorials/Extracting-Models-to-OBJ

Duckers@DESKTOP-4F3VOVP MINGW64 /c/ce2utils-main
$ scons -j 8
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
g++ -o src/baunpack.o -c -std=c++20 -Wall -Isrc -march=haswell -mtune=generic -O3 -fomit-frame-pointer -ffast-math src/baunpack.cpp
g++ -o src/common.o -c -std=c++20 -Wall -Isrc -march=haswell -mtune=generic -O3 -fomit-frame-pointer -ffast-math src/common.cpp
g++ -o src/filebuf.o -c -std=c++20 -Wall -Isrc -march=haswell -mtune=generic -O3 -fomit-frame-pointer -ffast-math src/filebuf.cpp
g++ -o src/zlib.o -c -std=c++20 -Wall -Isrc -march=haswell -mtune=generic -O3 -fomit-frame-pointer -ffast-math src/zlib.cpp
g++ -o src/ba2file.o -c -std=c++20 -Wall -Isrc -march=haswell -mtune=generic -O3 -fomit-frame-pointer -ffast-math src/ba2file.cpp
g++ -o src/esmfile.o -c -std=c++20 -Wall -Isrc -march=haswell -mtune=generic -O3 -fomit-frame-pointer -ffast-math src/esmfile.cpp
g++ -o src/stringdb.o -c -std=c++20 -Wall -Isrc -march=haswell -mtune=generic -O3 -fomit-frame-pointer -ffast-math src/stringdb.cpp
g++ -o src/btdfile.o -c -std=c++20 -Wall -Isrc -march=haswell -mtune=generic -O3 -fomit-frame-pointer -ffast-math src/btdfile.cpp
g++ -o src/ddstxt.o -c -std=c++20 -Wall -Isrc -march=haswell -mtune=generic -O3 -fomit-frame-pointer -ffast-math src/ddstxt.cpp
g++ -o src/downsamp.o -c -std=c++20 -Wall -Isrc -march=haswell -mtune=generic -O3 -fomit-frame-pointer -ffast-math src/downsamp.cpp
g++ -o src/esmdbase.o -c -std=c++20 -Wall -Isrc -march=haswell -mtune=generic -O3 -fomit-frame-pointer -ffast-math src/esmdbase.cpp
g++ -o src/nif_file.o -c -std=c++20 -Wall -Isrc -march=haswell -mtune=generic -O3 -fomit-frame-pointer -ffast-math src/nif_file.cpp
g++ -o src/meshfile.o -c -std=c++20 -Wall -Isrc -march=haswell -mtune=generic -O3 -fomit-frame-pointer -ffast-math src/meshfile.cpp
g++ -o src/material.o -c -std=c++20 -Wall -Isrc -march=haswell -mtune=generic -O3 -fomit-frame-pointer -ffast-math src/material.cpp
g++ -o src/landdata.o -c -std=c++20 -Wall -Isrc -march=haswell -mtune=generic -O3 -fomit-frame-pointer -ffast-math src/landdata.cpp
g++ -o src/plot3d.o -c -std=c++20 -Wall -Isrc -march=haswell -mtune=generic -O3 -fomit-frame-pointer -ffast-math src/plot3d.cpp
g++ -o src/landtxt.o -c -std=c++20 -Wall -Isrc -march=haswell -mtune=generic -O3 -fomit-frame-pointer -ffast-math src/landtxt.cpp
g++ -o src/terrmesh.o -c -std=c++20 -Wall -Isrc -march=haswell -mtune=generic -O3 -fomit-frame-pointer -ffast-math src/terrmesh.cpp
g++ -o src/render.o -c -std=c++20 -Wall -Isrc -march=haswell -mtune=generic -O3 -fomit-frame-pointer -ffast-math src/render.cpp
In file included from src/render.cpp:3:
src/render.hpp:12:10: fatal error: bgsmfile.hpp: No such file or directory
   12 | #include "bgsmfile.hpp"
      |          ^~~~~~~~~~~~~~
compilation terminated.
scons: *** [src/render.o] Error 1
In file included from src/plot3d.cpp:3:
src/plot3d.hpp: In member function 'bool Plot3D_TriShape::glowEnabled() const':
src/plot3d.hpp:92:19: error: request for member 'flags' in '((const Plot3D_TriShape*)this)->Plot3D_T
riShape::<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material* const' (
maybe you meant to use '->' ?)
   92 |     return bool(m.flags & BGSMFile::Flag_Glow);
      |                   ^~~~~
src/plot3d.hpp:92:27: error: 'BGSMFile' was not declared in this scope
   92 |     return bool(m.flags & BGSMFile::Flag_Glow);
      |                           ^~~~~~~~
src/plot3d.hpp: In member function 'bool Plot3D_TriShape::alphaBlendingEnabled() const':
src/plot3d.hpp:96:19: error: request for member 'flags' in '((const Plot3D_TriShape*)this)->Plot3D_T
riShape::<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material* const' (
maybe you meant to use '->' ?)
   96 |     return bool(m.flags & BGSMFile::Flag_TSAlphaBlending);
      |                   ^~~~~
src/plot3d.hpp:96:27: error: 'BGSMFile' was not declared in this scope
   96 |     return bool(m.flags & BGSMFile::Flag_TSAlphaBlending);
      |                           ^~~~~~~~
src/plot3d.cpp: In member function 'size_t Plot3D_TriShape::transformVertexData(const NIFFile::NIFVe
rtexTransform&)':
src/plot3d.cpp:56:9: error: request for member 'flags' in '((Plot3D_TriShape*)this)->Plot3D_TriShape
::<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material*' (maybe you mea
nt to use '->' ?)
   56 |   if (m.flags & BGSMFile::Flag_IsDecal) // decal
      |         ^~~~~
src/plot3d.cpp:56:17: error: 'BGSMFile' has not been declared
   56 |   if (m.flags & BGSMFile::Flag_IsDecal) // decal
      |                 ^~~~~~~~
In file included from src/plot3d.cpp:2:
src/plot3d.cpp:98:27: error: request for member 'flags' in '((Plot3D_TriShape*)this)->Plot3D_TriShap
e::<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material*' (maybe you me
ant to use '->' ?)
   98 |     if (BRANCH_UNLIKELY(m.flags & BGSMFile::Flag_TSWater))      // water
      |                           ^~~~~
src/common.hpp:82:61: note: in definition of macro 'BRANCH_UNLIKELY'
   82 | #  define BRANCH_UNLIKELY(x)    (__builtin_expect(long(bool(x)), 0L))
      |                                                             ^
src/plot3d.cpp:98:35: error: 'BGSMFile' was not declared in this scope
   98 |     if (BRANCH_UNLIKELY(m.flags & BGSMFile::Flag_TSWater))      // water
      |                                   ^~~~~~~~
src/common.hpp:82:61: note: in definition of macro 'BRANCH_UNLIKELY'
   82 | #  define BRANCH_UNLIKELY(x)    (__builtin_expect(long(bool(x)), 0L))
      |                                                             ^
src/plot3d.cpp:120:31: error: request for member 'textureScaleU' in '((Plot3D_TriShape*)this)->Plot3
D_TriShape::<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material*' (may
be you meant to use '->' ?)
  120 |       v.tangent[3] = txtU * m.textureScaleU + m.textureOffsetU;
      |                               ^~~~~~~~~~~~~
src/plot3d.cpp:120:49: error: request for member 'textureOffsetU' in '((Plot3D_TriShape*)this)->Plot
3D_TriShape::<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material*' (ma
ybe you meant to use '->' ?)
  120 |       v.tangent[3] = txtU * m.textureScaleU + m.textureOffsetU;
      |                                                 ^~~~~~~~~~~~~~
src/plot3d.cpp:122:33: error: request for member 'textureScaleV' in '((Plot3D_TriShape*)this)->Plot3
D_TriShape::<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material*' (may
be you meant to use '->' ?)
  122 |       v.bitangent[3] = txtV * m.textureScaleV + m.textureOffsetV;
      |                                 ^~~~~~~~~~~~~
src/plot3d.cpp:122:51: error: request for member 'textureOffsetV' in '((Plot3D_TriShape*)this)->Plot
3D_TriShape::<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material*' (ma
ybe you meant to use '->' ?)
  122 |       v.bitangent[3] = txtV * m.textureScaleV + m.textureOffsetV;
      |                                                   ^~~~~~~~~~~~~~
src/plot3d.cpp:126:11: error: request for member 'flags' in '((Plot3D_TriShape*)this)->Plot3D_TriSha
pe::<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material*' (maybe you m
eant to use '->' ?)
  126 |     if (m.flags & BGSMFile::Flag_IsTree)
      |           ^~~~~
src/plot3d.cpp:126:19: error: 'BGSMFile' has not been declared
  126 |     if (m.flags & BGSMFile::Flag_IsTree)
      |                   ^~~~~~~~
src/plot3d.cpp:139:13: error: request for member 'flags' in '((Plot3D_TriShape*)this)->Plot3D_TriSha
pe::<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material*' (maybe you m
eant to use '->' ?)
  139 |     if (!(m.flags & BGSMFile::Flag_TwoSided))
      |             ^~~~~
src/plot3d.cpp:139:21: error: 'BGSMFile' has not been declared
  139 |     if (!(m.flags & BGSMFile::Flag_TwoSided))
      |                     ^~~~~~~~
src/plot3d.cpp: In member function 'FloatVector4 Plot3D_TriShape::alphaBlend(FloatVector4, float, co
nst Fragment&) const':
src/plot3d.cpp:215:13: error: request for member 'alpha' in '((const Plot3D_TriShape*)this)->Plot3D_
TriShape::<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material* const'
(maybe you meant to use '->' ?)
  215 |   a = a * m.alpha * (1.0f / 255.0f);
      |             ^~~~~
src/plot3d.cpp:216:49: error: request for member 'alphaFlags' in '((const Plot3D_TriShape*)this)->Pl
ot3D_TriShape::<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material* co
nst' (maybe you meant to use '->' ?)
  216 |   unsigned char blendMode = (unsigned char) ((m.alphaFlags >> 1) & 0xFFU);
      |                                                 ^~~~~~~~~~
src/plot3d.cpp: In member function 'FloatVector4 Plot3D_TriShape::calculateLighting_SF(FloatVector4,
 FloatVector4, FloatVector4, float, FloatVector4, const Fragment&, float, float, float, int) const':
src/plot3d.cpp:235:10: error: request for member 's' in '((const Plot3D_TriShape*)this)->Plot3D_TriS
hape::<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material* const' (may
be you meant to use '->' ?)
  235 |   e *= m.s.envMapScale;
      |          ^
src/plot3d.cpp: In member function 'FloatVector4 Plot3D_TriShape::calculateLighting_SF(FloatVector4,
 const Fragment&) const':
src/plot3d.cpp:281:10: error: request for member 's' in '((const Plot3D_TriShape*)this)->Plot3D_TriS
hape::<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material* const' (may
be you meant to use '->' ?)
  281 |   e *= m.s.envMapScale;
      |          ^
src/plot3d.cpp: In member function 'FloatVector4 Plot3D_TriShape::calculateLighting_Water(FloatVecto
r4, float, Fragment&) const':
src/plot3d.cpp:368:21: error: request for member 'w' in '((const Plot3D_TriShape*)this)->Plot3D_TriS
hape::<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material* const' (may
be you meant to use '->' ?)
  368 |   FloatVector4  c(m.w.deepColor);
      |                     ^
src/plot3d.cpp:371:48: error: request for member 'w' in '((const Plot3D_TriShape*)this)->Plot3D_TriS
hape::<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material* const' (may
be you meant to use '->' ?)
  371 |   c += ((c0 - c) * a * (FloatVector4(1.0f) - m.w.shallowColor));
      |                                                ^
src/plot3d.cpp:374:11: error: request for member 'w' in '((const Plot3D_TriShape*)this)->Plot3D_TriS
hape::<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material* const' (may
be you meant to use '->' ?)
  374 |   e *= (m.w.envMapScale * lightColor[3]);
      |           ^
src/plot3d.cpp:375:18: error: request for member 'w' in '((const Plot3D_TriShape*)this)->Plot3D_TriS
hape::<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material* const' (may
be you meant to use '->' ?)
  375 |   specular *= (m.w.envMapScale * lightColor[3]);
      |                  ^
src/plot3d.cpp: In static member function 'static void Plot3D_TriShape::drawPixel_Water(Plot3D_TriSh
ape&, Fragment&)':
src/plot3d.cpp:386:15: error: request for member 'w' in 'p.Plot3D_TriShape::<anonymous>.NIFFile::NIF
TriShape::m', which is of pointer type 'const CE2Material*' (maybe you meant to use '->' ?)
  386 |   a = a * p.m.w.unused;         // -3.0 / maximum depth in pixels
      |               ^
src/plot3d.cpp: In static member function 'static void Plot3D_TriShape::drawPixel_Effect(Plot3D_TriS
hape&, Fragment&)':
src/plot3d.cpp:417:21: error: request for member 'e' in 'p.Plot3D_TriShape::<anonymous>.NIFFile::NIF
TriShape::m', which is of pointer type 'const CE2Material*' (maybe you meant to use '->' ?)
  417 |   smoothness *= p.m.e.specularSmoothness;
      |                     ^
src/plot3d.cpp:425:11: error: request for member 'e' in 'p.Plot3D_TriShape::<anonymous>.NIFFile::NIF
TriShape::m', which is of pointer type 'const CE2Material*' (maybe you meant to use '->' ?)
  425 |   if (p.m.e.envMapScale > 0.0f)
      |           ^
src/plot3d.cpp:428:14: error: request for member 'e' in 'p.Plot3D_TriShape::<anonymous>.NIFFile::NIF
TriShape::m', which is of pointer type 'const CE2Material*' (maybe you meant to use '->' ?)
  428 |     e *= p.m.e.envMapScale;
      |              ^
src/plot3d.cpp:436:11: error: request for member 'flags' in 'p.Plot3D_TriShape::<anonymous>.NIFFile:
:NIFTriShape::m', which is of pointer type 'const CE2Material*' (maybe you meant to use '->' ?)
  436 |   if (p.m.flags & BGSMFile::Flag_EffectLighting)
      |           ^~~~~
src/plot3d.cpp:436:19: error: 'BGSMFile' has not been declared
  436 |   if (p.m.flags & BGSMFile::Flag_EffectLighting)
      |                   ^~~~~~~~
src/plot3d.cpp:439:17: error: request for member 'e' in 'p.Plot3D_TriShape::<anonymous>.NIFFile::NIF
TriShape::m', which is of pointer type 'const CE2Material*' (maybe you meant to use '->' ?)
  439 |           * p.m.e.lightingInfluence);
      |                 ^
src/plot3d.cpp: In member function 'FloatVector4 Plot3D_TriShape::glowMap(const Fragment&) const':
src/plot3d.cpp:480:21: error: request for member 's' in '((const Plot3D_TriShape*)this)->Plot3D_TriS
hape::<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material* const' (may
be you meant to use '->' ?)
  480 |   FloatVector4  c(m.s.emissiveColor);
      |                     ^
src/plot3d.cpp:481:10: error: request for member 's' in '((const Plot3D_TriShape*)this)->Plot3D_TriS
hape::<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material* const' (may
be you meant to use '->' ?)
  481 |   c *= m.s.emissiveColor[3];
      |          ^
src/plot3d.cpp: In static member function 'static bool Plot3D_TriShape::getDiffuseColor_Effect(const
 Plot3D_TriShape&, FloatVector4&, Fragment&)':
src/plot3d.cpp:508:31: error: request for member 'e' in 'p.Plot3D_TriShape::<anonymous>.NIFFile::NIF
TriShape::m', which is of pointer type 'const CE2Material* const' (maybe you meant to use '->' ?)
  508 |   FloatVector4  baseColor(p.m.e.baseColor);
      |                               ^
src/plot3d.cpp:515:11: error: request for member 'flags' in 'p.Plot3D_TriShape::<anonymous>.NIFFile:
:NIFTriShape::m', which is of pointer type 'const CE2Material* const' (maybe you meant to use '->' ?
)
  515 |   if (p.m.flags & BGSMFile::Flag_FalloffEnabled)
      |           ^~~~~
src/plot3d.cpp:515:19: error: 'BGSMFile' has not been declared
  515 |   if (p.m.flags & BGSMFile::Flag_FalloffEnabled)
      |                   ^~~~~~~~
src/plot3d.cpp:517:21: error: request for member 'e' in 'p.Plot3D_TriShape::<anonymous>.NIFFile::NIF
TriShape::m', which is of pointer type 'const CE2Material* const' (maybe you meant to use '->' ?)
  517 |     float   d = p.m.e.falloffParams[1] - p.m.e.falloffParams[0];
      |                     ^
src/plot3d.cpp:517:46: error: request for member 'e' in 'p.Plot3D_TriShape::<anonymous>.NIFFile::NIF
TriShape::m', which is of pointer type 'const CE2Material* const' (maybe you meant to use '->' ?)
  517 |     float   d = p.m.e.falloffParams[1] - p.m.e.falloffParams[0];
      |                                              ^
src/plot3d.cpp:525:24: error: request for member 'e' in 'p.Plot3D_TriShape::<anonymous>.NIFFile::NIF
TriShape::m', which is of pointer type 'const CE2Material* const' (maybe you meant to use '->' ?)
  525 |       f = (nDotV - p.m.e.falloffParams[0]) / d;
      |                        ^
src/plot3d.cpp:528:14: error: request for member 'e' in 'p.Plot3D_TriShape::<anonymous>.NIFFile::NIF
TriShape::m', which is of pointer type 'const CE2Material* const' (maybe you meant to use '->' ?)
  528 |     f = (p.m.e.falloffParams[2] * (1.0f - f)) + (p.m.e.falloffParams[3] * f);
      |              ^
src/plot3d.cpp:528:54: error: request for member 'e' in 'p.Plot3D_TriShape::<anonymous>.NIFFile::NIF
TriShape::m', which is of pointer type 'const CE2Material* const' (maybe you meant to use '->' ?)
  528 |     f = (p.m.e.falloffParams[2] * (1.0f - f)) + (p.m.e.falloffParams[3] * f);
      |                                                      ^
src/plot3d.cpp:535:13: error: request for member 'flags' in 'p.Plot3D_TriShape::<anonymous>.NIFFile:
:NIFTriShape::m', which is of pointer type 'const CE2Material* const' (maybe you meant to use '->' ?
)
  535 |     if (p.m.flags & BGSMFile::Flag_GrayscaleToAlpha)
      |             ^~~~~
src/plot3d.cpp:535:21: error: 'BGSMFile' has not been declared
  535 |     if (p.m.flags & BGSMFile::Flag_GrayscaleToAlpha)
      |                     ^~~~~~~~
src/plot3d.cpp:539:17: error: request for member 'alphaThresholdFloat' in 'p.Plot3D_TriShape::<anony
mous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material* const' (maybe you meant
 to use '->' ?)
  539 |     if (a < p.m.alphaThresholdFloat)
      |                 ^~~~~~~~~~~~~~~~~~~
src/plot3d.cpp:547:17: error: request for member 'alphaThresholdFloat' in 'p.Plot3D_TriShape::<anony
mous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material* const' (maybe you meant
 to use '->' ?)
  547 |     if (a < p.m.alphaThresholdFloat)
      |                 ^~~~~~~~~~~~~~~~~~~
src/plot3d.cpp:549:22: error: request for member 'e' in 'p.Plot3D_TriShape::<anonymous>.NIFFile::NIF
TriShape::m', which is of pointer type 'const CE2Material* const' (maybe you meant to use '->' ?)
  549 |     baseColor *= p.m.e.baseColorScale;
      |                      ^
src/plot3d.cpp:556:27: error: request for member 'flags' in 'p.Plot3D_TriShape::<anonymous>.NIFFile:
:NIFTriShape::m', which is of pointer type 'const CE2Material* const' (maybe you meant to use '->' ?
)
  556 |   if (BRANCH_UNLIKELY(p.m.flags & BGSMFile::Flag_NoZWrite))
      |                           ^~~~~
src/common.hpp:82:61: note: in definition of macro 'BRANCH_UNLIKELY'
   82 | #  define BRANCH_UNLIKELY(x)    (__builtin_expect(long(bool(x)), 0L))
      |                                                             ^
src/plot3d.cpp:556:35: error: 'BGSMFile' was not declared in this scope
  556 |   if (BRANCH_UNLIKELY(p.m.flags & BGSMFile::Flag_NoZWrite))
      |                                   ^~~~~~~~
src/common.hpp:82:61: note: in definition of macro 'BRANCH_UNLIKELY'
   82 | #  define BRANCH_UNLIKELY(x)    (__builtin_expect(long(bool(x)), 0L))
      |                                                             ^
src/plot3d.cpp: In static member function 'static bool Plot3D_TriShape::getDiffuseColor_G(const Plot
3D_TriShape&, FloatVector4&, Fragment&)':
src/plot3d.cpp:572:31: error: request for member 'alphaThresholdFloat' in 'p.Plot3D_TriShape::<anony
mous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material* const' (maybe you meant
 to use '->' ?)
  572 |   if (BRANCH_UNLIKELY(a < p.m.alphaThresholdFloat))
      |                               ^~~~~~~~~~~~~~~~~~~
src/common.hpp:82:61: note: in definition of macro 'BRANCH_UNLIKELY'
   82 | #  define BRANCH_UNLIKELY(x)    (__builtin_expect(long(bool(x)), 0L))
      |                                                             ^
src/plot3d.cpp:576:19: error: request for member 's' in 'p.Plot3D_TriShape::<anonymous>.NIFFile::NIF
TriShape::m', which is of pointer type 'const CE2Material* const' (maybe you meant to use '->' ?)
  576 |   float   v = p.m.s.gradientMapV * vColor[0];
      |                   ^
src/plot3d.cpp: In static member function 'static bool Plot3D_TriShape::getDiffuseColor_C(const Plot
3D_TriShape&, FloatVector4&, Fragment&)':
src/plot3d.cpp:593:31: error: request for member 'alphaThresholdFloat' in 'p.Plot3D_TriShape::<anony
mous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material* const' (maybe you meant
 to use '->' ?)
  593 |   if (BRANCH_UNLIKELY(a < p.m.alphaThresholdFloat))
      |                               ^~~~~~~~~~~~~~~~~~~
src/common.hpp:82:61: note: in definition of macro 'BRANCH_UNLIKELY'
   82 | #  define BRANCH_UNLIKELY(x)    (__builtin_expect(long(bool(x)), 0L))
      |                                                             ^
src/plot3d.cpp: In member function 'void Plot3D_TriShape::drawTriShape(const NIFFile::NIFVertexTrans
form&, const DDSTexture* const*, unsigned int)':
src/plot3d.cpp:1077:30: error: request for member 'flags' in '((Plot3D_TriShape*)this)->Plot3D_TriSh
ape::<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material*' (maybe you
meant to use '->' ?)
 1077 |                         | (m.flags & BGSMFile::Flag_TSWater))))
      |                              ^~~~~
src/common.hpp:82:61: note: in definition of macro 'BRANCH_UNLIKELY'
   82 | #  define BRANCH_UNLIKELY(x)    (__builtin_expect(long(bool(x)), 0L))
      |                                                             ^
src/plot3d.cpp:1077:38: error: 'BGSMFile' was not declared in this scope
 1077 |                         | (m.flags & BGSMFile::Flag_TSWater))))
      |                                      ^~~~~~~~
src/common.hpp:82:61: note: in definition of macro 'BRANCH_UNLIKELY'
   82 | #  define BRANCH_UNLIKELY(x)    (__builtin_expect(long(bool(x)), 0L))
      |                                                             ^
src/common.hpp:82:51: error: expected primary-expression before 'long'
   82 | #  define BRANCH_UNLIKELY(x)    (__builtin_expect(long(bool(x)), 0L))
      |                                                   ^~~~
src/plot3d.cpp:1076:7: note: in expansion of macro 'BRANCH_UNLIKELY'
 1076 |   if (BRANCH_UNLIKELY(!((textureMask & 1U)
      |       ^~~~~~~~~~~~~~~
src/plot3d.cpp:1084:25: error: request for member 'flags' in '((Plot3D_TriShape*)this)->Plot3D_TriSh
ape::<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material*' (maybe you
meant to use '->' ?)
 1084 |   if (BRANCH_UNLIKELY(m.flags & BGSMFile::Flag_IsEffect))
      |                         ^~~~~
src/common.hpp:82:61: note: in definition of macro 'BRANCH_UNLIKELY'
   82 | #  define BRANCH_UNLIKELY(x)    (__builtin_expect(long(bool(x)), 0L))
      |                                                             ^
src/plot3d.cpp:1084:33: error: 'BGSMFile' was not declared in this scope
 1084 |   if (BRANCH_UNLIKELY(m.flags & BGSMFile::Flag_IsEffect))
      |                                 ^~~~~~~~
src/common.hpp:82:61: note: in definition of macro 'BRANCH_UNLIKELY'
   82 | #  define BRANCH_UNLIKELY(x)    (__builtin_expect(long(bool(x)), 0L))
      |                                                             ^
src/plot3d.cpp:1093:25: error: request for member 'flags' in '((Plot3D_TriShape*)this)->Plot3D_TriSh
ape::<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material*' (maybe you
meant to use '->' ?)
 1093 |   if (BRANCH_UNLIKELY(m.flags & BGSMFile::Flag_TSWater))
      |                         ^~~~~
src/common.hpp:82:61: note: in definition of macro 'BRANCH_UNLIKELY'
   82 | #  define BRANCH_UNLIKELY(x)    (__builtin_expect(long(bool(x)), 0L))
      |                                                             ^
src/plot3d.cpp:1093:33: error: 'BGSMFile' was not declared in this scope
 1093 |   if (BRANCH_UNLIKELY(m.flags & BGSMFile::Flag_TSWater))
      |                                 ^~~~~~~~
src/common.hpp:82:61: note: in definition of macro 'BRANCH_UNLIKELY'
   82 | #  define BRANCH_UNLIKELY(x)    (__builtin_expect(long(bool(x)), 0L))
      |                                                             ^
src/plot3d.cpp:1118:11: error: request for member 'flags' in '((Plot3D_TriShape*)this)->Plot3D_TriSh
ape::<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material*' (maybe you
meant to use '->' ?)
 1118 |   if (!(m.flags & BGSMFile::Flag_Glow))
      |           ^~~~~
src/plot3d.cpp:1118:19: error: 'BGSMFile' has not been declared
 1118 |   if (!(m.flags & BGSMFile::Flag_Glow))
      |                   ^~~~~~~~
src/plot3d.cpp: In member function 'void Plot3D_TriShape::drawWater(const DDSTexture* const*, unsign
ed int, float)':
src/plot3d.cpp:1189:5: error: request for member 'w' in '((Plot3D_TriShape*)this)->Plot3D_TriShape::
<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material*' (maybe you meant
 to use '->' ?)
 1189 |   m.w.unused = -3.0f / (m.w.maxDepth * viewScale);
      |     ^
src/plot3d.cpp:1189:27: error: request for member 'w' in '((Plot3D_TriShape*)this)->Plot3D_TriShape:
:<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material*' (maybe you mean
t to use '->' ?)
 1189 |   m.w.unused = -3.0f / (m.w.maxDepth * viewScale);
      |                           ^
src/plot3d.cpp:1196:7: error: request for member 's' in '((Plot3D_TriShape*)this)->Plot3D_TriShape::
<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material*' (maybe you meant
 to use '->' ?)
 1196 |     m.s.specularColor = FloatVector4(1.0f, 1.0f, 1.0f, m.w.envMapScale);
      |       ^
src/plot3d.cpp:1196:58: error: request for member 'w' in '((Plot3D_TriShape*)this)->Plot3D_TriShape:
:<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material*' (maybe you mean
t to use '->' ?)
 1196 |     m.s.specularColor = FloatVector4(1.0f, 1.0f, 1.0f, m.w.envMapScale);
      |                                                          ^
src/plot3d.cpp: In member function 'void Plot3D_TriShape::drawDecal(const NIFFile::NIFVertexTransfor
m&, const DDSTexture* const*, unsigned int, const NIFFile::NIFBounds&, uint32_t)':
src/plot3d.cpp:1309:25: error: request for member 'flags' in '((Plot3D_TriShape*)this)->Plot3D_TriSh
ape::<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material*' (maybe you
meant to use '->' ?)
 1309 |   if (BRANCH_UNLIKELY(m.flags
      |                         ^~~~~
src/common.hpp:82:61: note: in definition of macro 'BRANCH_UNLIKELY'
   82 | #  define BRANCH_UNLIKELY(x)    (__builtin_expect(long(bool(x)), 0L))
      |                                                             ^
src/plot3d.cpp:1310:26: error: 'BGSMFile' was not declared in this scope
 1310 |                       & (BGSMFile::Flag_IsEffect | BGSMFile::Flag_TSWater)))
      |                          ^~~~~~~~
src/common.hpp:82:61: note: in definition of macro 'BRANCH_UNLIKELY'
   82 | #  define BRANCH_UNLIKELY(x)    (__builtin_expect(long(bool(x)), 0L))
      |                                                             ^
src/common.hpp:82:51: error: expected primary-expression before 'long'
   82 | #  define BRANCH_UNLIKELY(x)    (__builtin_expect(long(bool(x)), 0L))
      |                                                   ^~~~
src/plot3d.cpp:1309:7: note: in expansion of macro 'BRANCH_UNLIKELY'
 1309 |   if (BRANCH_UNLIKELY(m.flags
      |       ^~~~~~~~~~~~~~~
src/plot3d.cpp:1389:11: error: request for member 'flags' in '((Plot3D_TriShape*)this)->Plot3D_TriSh
ape::<anonymous>.NIFFile::NIFTriShape::m', which is of pointer type 'const CE2Material*' (maybe you
meant to use '->' ?)
 1389 |   if (!(m.flags & BGSMFile::Flag_Glow))
      |           ^~~~~
src/plot3d.cpp:1389:19: error: 'BGSMFile' has not been declared
 1389 |   if (!(m.flags & BGSMFile::Flag_Glow))
      |                   ^~~~~~~~
scons: *** [src/plot3d.o] Error 1
scons: building terminated because of errors.

Duckers@DESKTOP-4F3VOVP MINGW64 /c/ce2utils-main

**Comment by Surasia** [comment]
the last few commits did not remove references to the FO4 material system causing these issues

**Comment by fo76utils** [comment]
The code is currently being reworked to replace the use of the material system from the older games. Until this is complete, you need to use the last tagged version from here: [https://github.com/fo76utils/ce2utils/tags](https://github.com/fo76utils/ce2utils/tags).

**Comment by DuckersMcQuack** [comment]
> The code is currently being reworked to replace the use of the material system from the older games. Until this is complete, you need to use the last tagged version from here: https://github.com/fo76utils/ce2utils/tags.

Thanks! That did the trick! :D
