### ISSUE TITLE
Extracting nif as obj

### ISSUE THREAD

**Issue by Max-Vincent** [fo76utils/ce2utils#3]
Hi, so i want to extract some Starfield models
my friend send me .ba2 meshes files & asked to extracts nif as obj with nif_info but i got this `nif_info: file materials/materialsbeta.cdb not found in archive`
with command `nif_info -obj -o maelstrom.obj "...\Starfield\Data" maelstrom.nif`

does it require all game files to extract it?

thanks

**Comment by Surasia** [comment]
It also requires the materials BA2 files.
