### ISSUE TITLE
Problem converting some files to obj

### ISSUE THREAD

**Issue by Gus-The-Forklift-Driver** [fo76utils/ce2utils#4]
Hi I have been using this great too to extract some meshes from Starfield, but I have encountered an issue. Some exported obj are messed up : 
![shipdockingbridge01.nif](https://github.com/fo76utils/ce2utils/assets/30367056/b478426f-eebf-4581-9bd7-13accf7fb8c4)

![bob_m.nif](https://github.com/fo76utils/ce2utils/assets/30367056/4d3e6177-1a19-437d-a526-18da41032308)

This might be caused by some messed up vertex order, but i have no idea how to fix this.

I am using this command : `.\nif_info.exe -obj -o obj\test8.obj path\to\Starfield\Data bob_m.nif`

I am on windows 10, using Starfield from steam, latest update, with file verified.

It might be unrelated but the files seems to have abnormal file sizes.

**Comment by fo76utils** [comment]
The issue seems to be that "bob_m.nif" matches multiple NIF files, so they are all converted and written to the output file. If you want to convert "meshes/actors/human/mesh/hairs/bob/bob_m.nif", try using the full path or "/bob_m.nif".

**Comment by Gus-The-Forklift-Driver** [comment]
Using the full path solved my issue.
Thank you very much.
